### PR TITLE
Bookings are patched before transitioning on PATCH requests

### LINKED ISSUE #23: Booking transition is being applied on old booking data
On `PATCH` requests, the bookings controller is transitioning bookings, as retrieved from the CQRS resource model, with any transition received in the request. This does not take into account any other data modifications that the booking would need to undergo, such as a change in its time.

Ideally, the built change set, that is eventually given to the UPDATE CQRS resource model, is applied on top of the existing booking _before_ the transition happens.

The bookings controller has access to a booking factory. Since both the change set and the booking are only guaranteed to be containers, a composite container can be used to "merge" the change set and the booking and give it to the factory as config. The result should be the patched booking.

### PR DESCRIPTION
**Pull request by mecha**
Fixes #23 

---- 

- [x] Recommended to merge #28 first!

-----

The following changes need to be made before merging:

- [x] Update version constraint for dependency `rebelcode/booking-transitioner` (currently set as `^0.2-alpha1`, which has a bug) when a new release is available for that package.
- [x] Update version constraint for dependency `dhii/sql-interface` (currently set as `dev-develop`) when a new release is available for that package.

### CODE REVIEW

**Review by XedinUnknown — COMMENTED** [review]
I have a few questions, mostly about `BookingsController#post()`:

1. In most places, we are not using the Booking itself, but are relying on the data of the booking. We are first inserting the data, then querying for it by ID. The only place right now where we seem to be using the Booking is to transition it. Can we avoid creating the booking instance for every process, since it doesn't seem to be required mostly?

2. The transitioner seems to be relying on the booking, more precisely on a state-aware instance. Does the transitioner need the state-aware in order to transition, or can it use only the state? If that is the case, we can do all of the operations without involving the Booking concept.

3. If I remember correctly, the transitioning now happens in memory, and the resulting state needs to be explicitly stored in the database. If that's true, then why do we need to persist a booking with "none" booking status before we transition it?

**Comment by mecha** [comment]
1. You're right. `BookingsController#post()` now needs revision, similar to `_patch()`. However, this is not the scope of this PR. I'll open a separate issue and PR to update `_post()`.

2. The booking concept is already not involved. As far as the transitioner knows, it gets a state-aware instance. We happen to be creating bookings, because our state-aware factory creates state-aware-bookings. I'm _very_ reluctant to change the concepts involved in this area since (a) it will likely require an interface update and (b) it already works rather well - don't fix what ain't broken and all that.

3. The transition graph in config is used as a strict authoritative reference of what transitions are allowed. As such, an initial state must exist that lists the available transitions from it. This is why the `none` status exists. As for why it needs to be persisted, it's because there are handlers that require a booking ID. Recall that we previously talked about ways to make handlers be able to work with bookings in memory - currently this is not the case and some of them require an ID for reference.

**Comment by XedinUnknown** [comment]
@mecha, please make sure that there are at least a card for revising `post()`, and one to document problem number 3, i.e. that some handlers (give examples) require booking ID, and that is why we must persist the booking first, which leads to code that is less optimized than... optimal.

**Comment by mecha** [comment]
@XedinUnknown Done!

**Review by XedinUnknown — APPROVED** [review]

**Pull request merged**
